### ISSUE TITLE
vnc_client_options a misleading name?

### ISSUE THREAD

**Issue by b2ag** [sdarwin/Ansible-VNC#12]
It seems `vnc_client_options` is option to the `vncserver`. Why is it called `vnc_client_options`?
https://github.com/sdarwin/Ansible-VNC/blob/ac9811f26682ea976c8d4058c1145f3694877215/defaults/main.yml#L37
https://github.com/sdarwin/Ansible-VNC/blob/ac9811f26682ea976c8d4058c1145f3694877215/templates/vncserver.j2#L9

**Comment by sdarwin** [comment]
Possibly you are right. I was quickly inventing variable names when writing this role. Even if they are options supplied to the vncserver, they represent settings that affect the client: what the client sees, or how the client connects.  The geometry setting can be changed in realtime after connecting.  I was thinking the 'desktop' view is the 'client'.

**Comment by b2ag** [comment]
It confused me cause it followed `vnc_server` and than made me think is `vnc_client_options` actually being options for another process? But `-localhost` gave it away as being a server option. I know it breaks legacy to change this, but, yeah, it confused me. Don't know what more to say or do :)

**Comment by b2ag** [comment]
You could use `{{ vnc_server_options }} {{ vnc_client_options }}` together to not break legacy for some month or years and already change it in `defaults/main.yml` and `README.md` and so on.

**Comment by sdarwin** [comment]
fixed in 9364d59

Closing the issue.

@b2ag it would be great if you could review the changes.  If there are problems let me know, the issue can be reopened.

Note: the newest versions of Tiger VNC, on Ubuntu 21 has switched to a different configuration.  The variables being discussed here are still relevant on older operating systems and other vnc packages.
